[phases.setup]
nixPkgs = [
  "php",
  "php82Extensions.pdo_pgsql",
  "phpExtensions.fileinfo",
  "phpPackages.composer",
  "nodejs_22"
]
cmds = [
    "chmod +x artisan"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "composer install",
  "npm install --production",
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = """
php artisan migrate --force --seed && \
php artisan serve --host=0.0.0.0 --port=${PORT}
"""
